<?php
/**
* PHP versions 4 and 5
*
* Copyright (c) 2005-2010 Pawson Laboratory, All Rights Reserved
*
* LICENSE:
*
* OpenFreezer is free software; you can redistribute it
* and/or modify it under the terms of the GNU General
* Public License as published by the Free Software Foundation;
* either version 3 of the License, or (at your option) any
* later version.
*
* OpenFreezer is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public
* License along with OpenFreezer.  If not, see <http://www.gnu.org/licenses/>.
*
* @author     Marina Olhovsky <olhosvky@lunenfeld.ca>
* @version    3.1
* @package Project
*
* @copyright  2005-2010 Pawson Laboratory
* @license    http://www.opensource.org/licenses/gpl-3.0.html GNU GPLv3
*/

/**
* Include/require statements
*/
	include_once "Classes/MemberLogin_Class.php";
	include_once "Classes/Member_Class.php";	
	include_once "Classes/Session_Var_Class.php";
	include_once "Classes/generalFunc_Class.php";	
	include_once "Project/ProjectFunctions.php";
	include_once "DatabaseConn.php";
	include "Classes/StopWatch.php";
	include "HeaderFunctions.php";

/**
 * Root file for Project module
 *
 * @author Marina Olhovsky <olhovsky@lunenfeld.ca>
 * @version 3.1
 * @package Project
 *
 * @copyright	2005-2010 Pawson Laboratory
 * @license    http://www.opensource.org/licenses/gpl-3.0.html GNU GPLv3
 *
*/
	header("Cache-control: private"); //IE 6 Fix 

	session_start();

	$loginBlock = new MemberLogin_Class();
	$loginBlock->loginCheck($_POST);

	// print header	
	outputMainHeader();

	?>
	<title>Project Page</title>

	<table height="100%">
		<table border="0" width="98%">
			<!-- Marina: March 4/08: Create a resizeable border -->
			<!--<tr>
				<td rowspan="100%" style="padding-left:0; padding-right:5px;">
					<div class="resizeable" onMouseOver="resize();"></div>
				</td>
			</tr>-->
		<?php
			if (isset($_SESSION["userinfo"]))
			{
				if( $loginBlock->verifyPermissions( basename( $_SERVER["PHP_SELF"] ), $_SESSION["userinfo"]->getUserID() ) ) 
				{
					$sessionChecker = new Session_Var_Class();
// 					$sessionChecker->checkSession_reagent();
					$sessionChecker->checkSession_all(); 	// july 17/07
					unset($sessionChecker);

					$currUserName = $_SESSION["userinfo"]->getDescription();

					?>
					<tr>
						<td>
						<?php	
							if ($_GET["View"] == "1")
							{
								// Create project
								printProjectCreationForm();
							}
							elseif ($_GET["View"] == "2")
							{
								// View Project
								if (!isset($_GET["pid"]))
								{
									printViewProjectForm();
								}
							}
							elseif ($_GET["View"] == "3")
							{
								// Delete project
								if (isset($_GET["Success"]))
								{
									if ($_GET["Success"] == 1)
									{
										// success
										echo "<span style=\"color:#FF0000; font-weight:bold\">Project deleted successfully.</span><BR/><BR/>";
										echo "<a href=\"" . $_SERVER["PHP_SELF"]. "?View=2\">Back to Project list</a>";
									}
									else
									{
										// Project could not be deleted
										echo "<span style=\"color:#FF0000; font-weight:bold\">Project " . $_GET["pID"] . " could not be deleted, since there are reagents associated with it.</span><BR/><BR/>";
										
										if (isset($_GET["pID"]))
										{
											//echo "<a href=\"" . $_SERVER["PHP_SELF"]. "?View=2&pid=" . $_GET["pID"] . "\">Back to Project Details</a>";
											?>
											<span class="linkShow" onClick="redirectToProjectDetailedView(<?php echo $_GET["pID"]; ?>)">Back to Project Details</span>
											
											<FORM id="viewProjectForm" method="POST" action="<?php echo $cgi_path . "project_request_handler.py"; ?>">
												<INPUT type="hidden" id="view_packet_hidden" name="view_packet">
												<INPUT type="hidden" ID="username_hidden" NAME="username" VALUE="<?php echo $currUserName; ?>">

											</FORM>
											<?php
										}
									}
								}
								else
								{
									printProjectDeletionForm($_GET["Result"]);
								}
							}
							elseif ($_GET["View"] == "4")
							{
								// Detailed Project View, incl. Modification
								
								// Page content was generated by Python and stored in a file
								/*
								if (isset($_GET["fd"]) && $_GET["fd"] != "")
								{
									$project_file = "/tmp/tmp" . $_GET["fd"] . ".html";
									//$project_file = "pictures/project.html";
									$project_fh = fopen($project_file, 'r');
									$project_page = fread($project_fh, filesize($project_file));
									echo $project_page;
									
									// delete temp file
									unlink($project_file);
								}*/
							}
						?>
						</td>
					</tr>
					<?php
				}
				else
				{					
					echo "<tr><td class=\"warning\">";
					echo "You are not authorized to view this page.  Please contact the site administrator.";
					echo "</td></tr>";
				}
			}
			else
			{
				echo "<tr><td class=\"warning\">";
				echo "You need to log in to access this page.";
				echo "</td></tr>";
			}
		?>	
		</table>
	</table>
	<?php

	outputMainFooter();
	
/*********************************************************************
	FUNCTIONS
*********************************************************************/
/**
 * Output project creation page
 *
 * @author Marina Olhovsky <olhovsky@lunenfeld.ca>
 * @version 3.1
*/
function printProjectCreationForm()
{
	global $cgi_path;
	
	$currUserName = $_SESSION["userinfo"]->getDescription();

	?>
	<FORM NAME="create_project_form" METHOD="POST" ACTION="<?php echo $cgi_path . "project_request_handler.py"; ?>" onSubmit="return verifyProjectOwner('projectOwnersList') && verifyProjectName('packet_name') && verifyProjectDescr('packet_descr') && verifyMembers('readers_target_list') && verifyMembers('writers_target_list');">
		
		<!-- Pass user info as a hidden form value to Python -->
		<INPUT type="hidden" ID="username_hidden" NAME="username" VALUE="<?php echo $currUserName; ?>">
		
		<DIV style="width:775px; font-weight:bold; color:#0000FF; text-align:center; padding-bottom: 5px;">CREATE A NEW PROJECT</DIV>

		<TABLE width="775px" cellpadding="4" cellspacing="2">
		
			<TH colspan="3" style="text-align:left; color:#0000FF; border-top: 1px groove black; padding-top: 10px;">
				Project Details:
			</TH>


			<TR>
				<TD class="createViewColName">
					Project ID
				</TD>

				<TD colspan="2" class="createViewColValue">
					<?php echo getMaxProjectID(); ?>
					<INPUT TYPE="HIDDEN" NAME="packetID" VALUE="<?php echo getMaxProjectID(); ?>">
				</TD>
			</TR>
			
			<TR>
				<TD class="createViewColName">
					Project Owner
					<span style="font-size:10pt; color:#FF0000; font-weight:bold">*</span>
				</TD>

				<TD colspan="2" class="createViewColValue">
				
					<SELECT ID="projectOwnersList" NAME="packetOwner">

						<OPTION selected value="default">Select project owner</OPTION>
					
						<?php 
							// Modified June 19/07, Marina: Show CREATORS in owners list - writers will be shown in members list further down
							$creators = getCreatorsList();
							
							foreach ($creators as $key => $value)
							{
								// Pre-select current user's name by default
								if ($key == $_SESSION["userinfo"]->getUserID())
								{
									echo "<OPTION SELECTED value=\"" . $key . "\">" . $value . "</OPTION>";
								}
								else
								{
									echo "<OPTION value=\"" . $key . "\">" . $value . "</OPTION>";
								}
							}
						?>
					</SELECT>

					<DIV ID="projectOwnerWarning" STYLE="display:none; color:#FF0000; font-weight:normal;">
						<BR>Please select a name from the list above.
					</DIV>
				</TD>
			</TR>

			<TR>
				<TD class="createViewColName">
					<a name="select_members"></a>
					Project Name
					<span style="font-size:10pt; color:#FF0000; font-weight:bold">*</span>
				</TD>

				<TD colspan="2" class="createViewColValue">
					<INPUT TYPE="TEXT" SIZE="35px" id="packet_name" NAME="packetName">

					<DIV ID="projectNameWarning" STYLE="display:none; color:#FF0000; font-weight:normal;">
						<BR>Please provide a project name.
					</DIV>
				</TD>
			</TR>

			<TR>
				<TD class="createViewColName" nowrap>
					Project Description

					<!-- June 3, 2010: make description mandatory too -->
					<span style="font-size:10pt; color:#FF0000; font-weight:bold">*</span>
				</TD>

				<TD colspan="2" class="createViewColValue" style="padding-bottom: 10px;">
					<INPUT TYPE="TEXT" SIZE="75px" NAME="packetDescription" id="packet_descr">

					<DIV ID="projectDescrWarning" STYLE="display:none; color:#FF0000; font-weight:normal;">
						<BR>Please provide a project description.
					</DIV>
				</TD>
			</TR>
			
			
			<TR>
				<TD class="createViewColName">
					Access type:
				</TD>

				<TD colspan="2" style="padding-bottom: 10px;">
					&nbsp;&nbsp;<INPUT TYPE="RADIO" NAME="private_or_public" VALUE="public">Public&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					<INPUT TYPE="RADIO" NAME="private_or_public" VALUE="private" checked>Private
				</TD>
			</TR>
			
			<TR>
				<TD colspan="2" style="font-size:8pt; font-weight:bold;">
					A Public project means that reagents in this project may be viewed by ALL OpenFreezer users.  Declaring a project Private hides its content from users who are not explicit members in this project.  Modification of both Public and Private project content is restricted to project members with write access.
				</TD>
			</TR>
			
			
			<TR>
				<TD colspan="3" style="font-weight:bold; text-align:left; color:#0000FF; padding-top: 10px; border-top: 1px groove black;">
						Project Members:
				</TD>
			</TR>

			<tr>
				<td colspan="3" style="padding-top:8px; font-weight:bold;">
					Assign members from one or more of the following laboratories to this project:
				</td>
			</tr>

			<TR>
				<td style="vertical-align:top; padding-top:10px" nowrap colspan="3">
					Laboratory:&nbsp;&nbsp;&nbsp;
					
					<?php 
						// Modified July 3/07: Show only labs with WRITE access --> Aug 17/07: No, show all labs
						//$writerCategoryID = findCategoryID("Writer");
						printLabList();
					?>
					<BR/>
					<P style="margin-top:15px">Members:</span>
				</td>
			</tr>

			<tr>
				<td style="vertical-align:top; padding-top:10px; width:200px; padding-left:10px; white-space:nowrap">
					<P>
					<?php
						$labList = getLabList();
						$currLabID = $_SESSION["userinfo"]->getLabID();

						foreach ($labList as $labID => $labName)
						{
							$display = ($labID == $currLabID) ? "inline" : "none";

							$users = getAllUsers($labID);
							
							echo "<SELECT id=\"lab_source_list_" . $labID . "\" name=\"labSourceMembers_" . $labID . "\" multiple size=\"10\"  style=\"display: " . $display . "\">";

							foreach ($users as $key => $value)
							{
								echo "<OPTION id=\"user_" . $key . "_lab_" . $labID . "\" value=\"" . $key . "\">" . $value . "</OPTION>";
							}

							echo "</SELECT>";
						}
					?>
					</P>
					<!-- April 3/09: Changed function name from selectAllUsers() to selectAll() (renamed function in menu.js for generalization, it can be used to select all elements in any list, not just Users) -->
					<INPUT TYPE="checkbox" onClick="selectAll(this.id, 'lab_source_list_' + getSelectedLab())" id="add_all_chkbx"> Select All Members</INPUT>
				</td>
			
				<TD style="vertical-align:top; padding-top:15px; padding-left:15px; ">

					For selected members, define their access level to this project:<BR/>

					<P style="font-size:9pt; margin-top:5px;">
						<input type="radio" id="access_level_radio_read" name="access_levels" value="read" checked>Read-Only &nbsp;&nbsp;&nbsp;
						<input type="radio" id="access_level_radio_write" name="access_levels" value="write">Write &nbsp;&nbsp;&nbsp;
						<input style="margin-top:4px" onclick="addMembers('lab_source_list_' + getSelectedLab(), getSelectedRole('1'))" value="Go" type="button"></INPUT>
						<BR/>
					</P>
					
					<P style="font-size: 8pt; border-top: 1px groove black; padding-top: 5px; padding-bottom: 5px">
						Access levels: <BR/><BR/>

						<span style="font-size: 8pt; margin-left: 9px; font-weight:bold; ">&#45; Read-Only:</span>  May view reagents in this project but may NOT modify them or add new reagents<BR/>

						<span style="font-size: 8pt; margin-left: 9px; font-weight:bold;">&#45; Write:</span>  May create and modify reagents in this project but may NOT change project details or add/remove members to/from this project<BR/>

						<P><span style="font-size: 8pt; font-weight:bold; color:#FF0000; text-align:center"><u>Please note</u>: Only users who have at least Write access to OpenFreezer may be added to the writers list
					</P>
				</TD>
			</tr>

			<tr>
				<TD colspan="3" style="padding-top:10px; border-top: 1px groove black">
				
					<table width="750px">
					
						<th colspan="3" style="text-align:left; padding-bottom:5px; border-bottom: 1px solid black">
							Members currently assigned to this project:<BR/>
							<span style="font-weight:normal">(You may edit the lists by selecting member names and choosing an action below)</span>
						</th>
						
						<tr>
							<td style="padding-left:5px; padding-top:5px; padding-bottom:5px; border-right: 1px solid black" width="240px">
								<span style="font-size:8pt; font-weight:bold;">Readers:</span><BR/>
								<SELECT style="margin-top:5px;" id="readers_target_list" name="readersTargetList" multiple size="12"></SELECT><BR/>
								
								<!-- April 3/09: Changed function name from selectAllUsers() to selectAll() (renamed function in menu.js for generalization, it can be used to select all elements in any list, not just Users) -->
								<INPUT TYPE="checkbox" style="margin-top:10px" onClick="selectAll(this.id, 'readers_target_list')" id="select_all_reader_chkbx"> Select All</INPUT>
							</td>
							
							<!-- June 20/2007 -->
							<td width="180px" style="text-align:center; border-right: 1px solid black">
								<input onclick="addMembers('readers_target_list', 'write')" value="   Make Writer >>" type="button"></INPUT><BR/>
								<input style="margin-top:30px;" onclick="addMembers('writers_target_list', 'read')" value="<< Make Reader" type="button"></INPUT><BR/>
								<input style="margin-top:30px;" onclick="removeProjectMembers()" value="Remove Selected" type="button"></INPUT>
							</td>
							
							<td style="padding-left:30px; padding-top:5px; padding-bottom:5px;">
								
								<span style="font-size:8pt; font-weight:bold;">Writers:</span><BR/>
								
								<SELECT style="margin-top:5px;" id="writers_target_list" name="writersTargetList" multiple size="12"></SELECT><BR/>
								
								<!-- April 3/09: Changed function name from selectAll() to selectAll() (renamed function in menu.js for generalization, it can be used to select all elements in any list, not just Users) -->
								<INPUT style="margin-top:10px;" TYPE="checkbox" onClick="selectAll(this.id, 'writers_target_list')" id="select_all_writer_chkbx"> Select All</INPUT>
							</td>
						
						</tr>
					</table>
				</td>
			</tr>
						
			<TR>
				<TD colspan="3" style="padding-top:10px; border-top: 1px groove black;">
					<INPUT TYPE="SUBMIT" NAME="create_project" VALUE="Create Project" onClick="addProjectOwnerToWritersList(); selectAllElements('readers_target_list'); selectAllElements('writers_target_list'); alert('Please note: If your project writers list contains names of users who have read-only access to OpenFreezer, their names will be removed from the list during saving.'); ">
				</TD>
			</TR>
		</TABLE>
	</FORM>
	<?php
}

/**
 * Fetch the NEXT highest project ID from the database (i.e. highest project ID + 1)
 *
 * Do NOT check status; e.g. if there are 16 packets in total, and packet 9 is DEP, the new project ID would be 17 and not 9 (i.e. DEP PACKETS ARE **NOT** REPLACED!!!)
 *
 * @author Marina Olhovsky <olhovsky@lunenfeld.ca>
 * @version 3.1
 * @return INT
*/
function getMaxProjectID()
{
	global $conn;
	
	$newProjectID = 0;
	
	// Fetch the next highest project ID, WITHOUT checking status; e.g. if there are 16 packets in total, and packet 9 is DEP, the new project ID would be 17 and not 9 (i.e. DEP PACKETS ARE **NOT** REPLACED!!!)
	$project_set = mysql_query("SELECT MAX(packetID) AS projectID FROM Packets_tbl", $conn) or die("Cannot fetch maximum project ID: " . mysql_error());
	
	if ($project_ar = mysql_fetch_array($project_set, MYSQL_ASSOC))
	{
		$newProjectID = $project_ar["projectID"] + 1;
	}
	
	return $newProjectID;
}


/**
 * Fetch the list of all users who belong to category 'Creators'
 *
 * @author Marina Olhovsky <olhovsky@lunenfeld.ca>
 * @version 3.1
 *
 * @return Array Dictionary of (userID => username) tuples
*/
function getCreatorsList()
{
	global $conn;

	$writers = array();
	
	$writers_rs = mysql_query("SELECT userID, CONCAT(u.firstname, \" \", u.lastname) AS username FROM Users_tbl u, UserCategories_tbl c WHERE c.category = 'Creator' AND u.category <= c.categoryID AND c.status='ACTIVE' AND u.description <>'' AND u.firstname <>'' AND u.lastname <>'' AND u.status='ACTIVE' ORDER BY username", $conn) or die("Cannot fetch creators: " . mysql_error());
	
	while ($writers_ar = mysql_fetch_array($writers_rs, MYSQL_ASSOC))
	{
		$uid = $writers_ar["userID"];
		$username = $writers_ar["username"];
		$writers[$uid] = $username;
	}

	return $writers;
}


/**
 * Select all users from the lab identified by $labID
 *
 * @author Marina Olhovsky <olhovsky@lunenfeld.ca>
 * @version 3.1
 *
 * @return Array Dictionary of (userID => full person name) tuples (i.e. '1' => 'John Doe')
*/
function getAllUsers($labID)
{
	global $conn;

	$users = array();
	
	// August 17/07, Marina: Select ALL users in a lab, not only >= 'writers'
	$users_rs = mysql_query("SELECT userID, username, CONCAT(firstname, \" \", lastname) AS uname FROM Users_tbl WHERE labID='" . $labID . "' AND status='ACTIVE' ORDER BY uname", $conn) or die("Cannot fetch users: " . mysql_error());
	
	while ($users_ar = mysql_fetch_array($users_rs, MYSQL_ASSOC))
	{
		$uid = $users_ar["userID"];
		$username = $users_ar["username"];
		$uname = $users_ar["uname"];
		
		if ( strlen(trim($uname)) > 0 && $username != 'guest' )
		{
			$users[$uid] = $uname;
		}
	}
	
	return $users;
}

/**
 * Print project deletion form -- NOT actively used in this version
 *
 * @author Marina Olhovsky <olhovsky@lunenfeld.ca>
 * @version 3.1
 *
 * @param STRING $success
*/
function printProjectDeletionForm($success="")
{
	global $cgi_path;
	
	$currUserID = $_SESSION["userinfo"]->getUserID();
	$currUserName = $_SESSION["userinfo"]->getDescription();
	$currUserCategory = $_SESSION["userinfo"]->getCategory();

	// Show ALL projects for Admins; and only projects owner by current user for users with lower access privileges
	// Therefore, if user is not admin, check if they own any projects.  If they don't, don't output a deletion form for them at all
	$currUserProjects = getAllUserProjects($currUserID);
	
	// Now, an owner can delete all of his/her projects and be left with 0 - but we don't want to show a warning in this case!  So check if we're here after deletion has taken place. If 'success' argument is an empty string, deletion has not yet been attempted, in which case can issue a zero-projects warning
	if ($success == "")
	{
		// hard-coding categirt value '1' for 'Admin' - selection easy but change at first opportunity
		if ( ($currUserCategory == '1') || (count($currUserProjects) > 0) )
		{
			?>
			<FORM METHOD="POST" ACTION="<?php echo $cgi_path . "project_request_handler.py"; ?>" onSubmit="return verifyProjectDeletion('packetList', 'delete_project');">

				<!-- HACK: Pass user info as a hidden form value - can't think of a better way to pass it through session from PHP to Python -->
				<INPUT type="hidden" ID="username_hidden" NAME="username" VALUE="<?php echo $currUserName; ?>">

				<TABLE width="773px" border="1px" frame="box" rules="none" cellpadding="5">

					<TH class="title">
						DELETE A PROJECT
					</TH>

					<TR>
						<TD>
							<FIELDSET>			
								<LEGEND>&nbsp;Please select one or more projects that you wish to delete:&nbsp;</LEGEND>

									<P><div class="warning" id="project_warning">&nbsp;Please select one ore more Project IDs from the dropdown list</div></P>
									<?php
										printPacketList(1, "", 1);
									?>
								</LEGEND>			
							</FIELDSET>
						</TD>
					</TR>

					<TR>
						<TD>
							<P>		
								<INPUT TYPE="SUBMIT" NAME="delete_project" VALUE="Delete Selected Projects">
							</P>
						</TD>
					</TR>
				</TABLE>
			</FORM>
			<?php
		}
		else
		{
			echo "<span style=\"font-weight:bold\">Only project owners or administrators are authorized to delete projects.</span><BR/><BR/><BR/><BR/><BR/><BR/><BR/><BR/><BR/><BR/>";
		}
	}
}

/**
 * Retrive all projects owned by the user identified by $userID
 *
 * @author Marina Olhovsky <olhovsky@lunenfeld.ca>
 * @version 3.1
 *
 * @return Array List of project IDs
*/
function getAllUserProjects($userID)
{
	global $conn;
	
	$userProjects = array();
	$currUserID = $_SESSION["userinfo"]->getUserID();
	
	$query = "SELECT p.packetID as packetID, p.packetName as packetName, u.lastname as owner FROM Packets_tbl p, Users_tbl u WHERE p.ownerID='" . $currUserID . "' AND p.ownerID=u.userID AND p.status='ACTIVE'";	
	$find_name_rs = mysql_query($query, $conn) or die("Error fetching packet ID:" . mysql_error());

	while ($find_name_ar = mysql_fetch_array($find_name_rs, MYSQL_ASSOC))
	{
		$userProjects[] = $find_name_ar["packetID"];
	}
	
	return $userProjects;
}

/**
 * Output project selection page (print dropdown list of projects accessible by the user; redirect to details page for selected project)
 *
 * @author Marina Olhovsky <olhovsky@lunenfeld.ca>
 * @version 3.1
*/
function printViewProjectForm()
{
	global $cgi_path;
	global $conn;
	
	$currUserName = $_SESSION["userinfo"]->getDescription();
	$currUserID = $_SESSION["userinfo"]->getUserID();
	?>
	<FORM METHOD="POST" ACTION="<?php echo $cgi_path . "project_request_handler.py"; ?>" onSubmit="return verifyProject();">
		
		<!-- Pass user info as a hidden form value to Python -->
		<INPUT type="hidden" ID="username_hidden" NAME="username" VALUE="<?php echo $currUserName; ?>">
		
		<TABLE width="775px" border="1px" frame="box" rules="none" cellpadding="5">
		
			<TH colspan="2" class="title">
				SELECT A PROJECT TO VIEW AND MODIFY
			</TH>

			<TR>
				<TD colspan="2">
					<FIELDSET>
						<LEGEND>&nbsp;Please select a project for viewing and/or modification:&nbsp;</LEGEND>
						
						<TABLE>
							<TR>
								<TD>
									<?php
									$currUserCategory = $_SESSION["userinfo"]->getCategory();

									// Show ALL projects for Admins; for users with lower access privileges only show projects accessible by current user
									if ($currUserCategory == $_SESSION["userCategoryNames"]['Admin'])
									{
										printPacketList(0);
									}
									else
									{
										// Select projects current user is member of, plus all public projects
										$uProject_set = mysql_query("SELECT DISTINCT p.packetID as packetID, p.packetName as packetName, u.lastname as owner FROM ProjectMembers_tbl m, Packets_tbl p, Users_tbl u WHERE m.memberID='" . $currUserID . "' AND p.ownerID=u.userID AND m.packetID=p.packetID AND p.status='ACTIVE' UNION SELECT DISTINCT p.packetID as packetID, p.packetName as packetName, u.lastname as owner FROM Packets_tbl p, Users_tbl u WHERE p.is_private='FALSE' AND p.ownerID=u.userID AND p.status='ACTIVE' ORDER BY packetID", $conn) or die("Cannot fetch user projects: " . mysql_error());

										while ($uProjects = mysql_fetch_array($uProject_set, MYSQL_ASSOC))
										{
											$pID = $uProjects["packetID"];
											$temp_packet = $pID . ": " . $uProjects["owner"] . ": " . $uProjects["packetName"];
											$userProjects[$pID] = $temp_packet;
										}

										// Alternatively, the user may be a project owner, in which case there would be no explicit entry in ProjectMembers_tbl
										$owner_set = mysql_query("SELECT DISTINCT p.packetID as packetID, p.packetName as packetName, u.lastname as owner FROM Packets_tbl p, Users_tbl u  WHERE p.ownerID='" . $currUserID . "' AND p.ownerID=u.userID AND p.status='ACTIVE' ORDER BY p.packetID") or die("Cannot fetch user projects: " . mysql_error());

										while ($owners = mysql_fetch_array($owner_set, MYSQL_ASSOC))
										{
											$pID = $owners["packetID"];
											$temp_packet = $pID . ": " . $owners["owner"] . ": " . $owners["packetName"];
											$userProjects[$pID] = $temp_packet;
										}
										
										$userProjects = array_unique($userProjects);
										
										echo "<SELECT id=\"packetList\" name=\"packets\">";
										echo "<OPTION value=\"0\">Select Project</OPTION>";

										foreach ($userProjects as $pID => $project)
										{
											echo "<OPTION value=\"" . $pID . "\">" . $project . "</OPTION>";
										}
										
										echo "</SELECT>";
									}
									?>
								</TD>
							</TR>
						</TABLE>

						<div class="warning" id="project_warning">&nbsp;Please select a Project ID from the dropdown list to view</div>

					</FIELDSET>
				</TD>
			</TR>
						
			<TR>
				<TD style="padding-left:25px;">
					<P>		
						<INPUT TYPE="SUBMIT" id="viewProject" NAME="view_project" VALUE="Go">
					</P>
				</TD>
			</TR>
		</TABLE>
	</FORM>
	<?php
}

/**
 * Output list of laboratories
 *
 * @author Marina Olhovsky <olhovsky@lunenfeld.ca>
 * @version 3.1
 *
 * @param STRING $oper List action (not actively used in this version)
*/
function printLabList($oper="")
{
	global $conn;
	
	$labList = array();

	$labList_rs = mysql_query("SELECT labID, lab_name FROM LabInfo_tbl WHERE status='ACTIVE' ORDER BY lab_name", $conn) or die("Error selecting labs: " . mysql_error());
	
	while ($labList_ar = mysql_fetch_array($labList_rs, MYSQL_ASSOC))
	{
		$labID = $labList_ar["labID"];
		$labName = $labList_ar["lab_name"];
		
		$labList[$labID] = $labName;
	}
	
	$currLabID = $_SESSION["userinfo"]->getLabID();
	
	echo "<SELECT id=\"labList\" name=\"labs\" onChange=\"showLabMembersList()\">";

	foreach ($labList as $key => $value)
	{
		$selected = ($key == $currLabID) ? "selected" : "";

		?>
		<OPTION ID="<?php echo $key; ?>" NAME="lab_optn" VALUE="<?php echo $key; ?>" <?php echo $selected; ?>>
		<?php 
			echo $value; 
		?>		
		</OPTION>
		<?php
	}

	echo "</SELECT>";
}

/**
 * Retrieve all laboratories from the database
 *
 * @author Marina Olhovsky <olhovsky@lunenfeld.ca>
 * @version 3.1
 *
 * @return Array Dictionary of (labID => labName) tuples
*/
function getLabList()
{
	global $conn;

	$lab_rs = mysql_query("SELECT labID, lab_name FROM LabInfo_tbl WHERE status='ACTIVE' ORDER BY lab_name", $conn) or die("Cannot select labs: " . mysql_error());

	$labs = array();

	while ($lab_ar = mysql_fetch_array($lab_rs, MYSQL_ASSOC))
	{
		$labID = $lab_ar["labID"];
		$labName = $lab_ar["lab_name"];

		$labs[$labID] = $labName;
	}

	return $labs;
}
mysql_close($conn);
?>