<?php
/**
* PHP versions 4 and 5
*
* Copyright (c) 2005-2010 Pawson Laboratory, All Rights Reserved
*
* LICENSE:
*
* OpenFreezer is free software; you can redistribute it
* and/or modify it under the terms of the GNU General
* Public License as published by the Free Software Foundation;
* either version 3 of the License, or (at your option) any
* later version.
*
* OpenFreezer is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public
* License along with OpenFreezer.  If not, see <http://www.gnu.org/licenses/>.
*
* @author     Marina Olhovsky <olhosvky@lunenfeld.ca>
* @version    3.1
* @package User
*
* @copyright  2005-2010 Pawson Laboratory
* @license    http://www.opensource.org/licenses/gpl-3.0.html GNU GPLv3
*/

/**
* Include/require statements
*/
	include_once "Classes/MemberLogin_Class.php";

	include_once "Project/ProjectFunctions.php";		// Aug 10/07; it includes Member_Class so don't need to redeclare it here

	include_once "Classes/Session_Var_Class.php";
	include_once "Classes/generalFunc_Class.php";

	include "Classes/StopWatch.php";

	// Feb. 16, 2011: Reagent_Background_Class is needed in Order_Class, but cannot place the 'include' statement in Order_Class.php because it becomes a circular reference.  Place it here, before 'include Order_CLass'
	include "Reagent/Reagent_Background_Class.php";

	// Jan. 23/08: Order reagents
	include "Location/Location_Funct_Class.php";
	include "Classes/Order_Class.php";
	
	include_once "DatabaseConn.php";
	include "HeaderFunctions.php";

	include_once "menu.js";
/**
 * Root file for User module
 *
 * @author Marina Olhovsky <olhovsky@lunenfeld.ca>
 * @version 3.1
 * @package User
 *
 * @copyright	2005-2010 Pawson Laboratory
 * @license    http://www.opensource.org/licenses/gpl-3.0.html GNU GPLv3
 *
*/
	/**
	 * A constant used to define table width on User module views
	 * @global INT $Const_Table_Width
	*/
	global $Const_Table_Width;

	$colspan_const = 0;

	/**
	 * Hostname (e.g. http://openfreezer.org/)
	 * @global STRING $hostname
	*/
	global $hostname;

	header("Cache-control: private"); //IE 6 Fix

	session_start();

	$loginBlock = new MemberLogin_Class();
	$loginBlock->loginCheck($_POST);

	// print header
	outputMainHeader();

	/**
	 * Email address of Dr Karen Colwill, the biologist leader of OpenFreezer: colwill@lunenfeld.ca
	 * @global STRING $mail_biologist
	*/
	global $mail_biologist;		// June 3, 2010

	/**
	 * Email address of Marina Olhovsky, the programmer of OpenFreezer: olhovsky@lunenfeld.ca
	 * @global STRING $mail_programmer
	*/
	global $mail_programmer;

	?>
	<title>Users and Labs</title>
	
	<div class="main">
		<table border="0" valign="middle">
			<!-- Marina: March 4/08: Create a resizeable border -->
			<!--<tr>
				<td rowspan="100%" style="padding-left:0; padding-right:5px;">
					<div class="resizeable" onMouseOver="resize();"></div>
				</td>
			</tr>-->
			<?php
			if (isset($_SESSION["userinfo"]))
			{
				if ($loginBlock->verifyPermissions(basename($_SERVER["PHP_SELF"]), $_SESSION["userinfo"]->getUserID()))
				{
					$sessionChecker = new Session_Var_Class();
					$sessionChecker->checkSession_all();
					unset($sessionChecker);

					$currUserID = $_SESSION["userinfo"]->getUserID();
					$currUserName = $_SESSION["userinfo"]->getDescription();

					?>
					<tr>
						<td>
							<?php
							if ($_GET["View"] == "1")
							{
								if ($_SESSION["userinfo"]->getCategory() == 1)
								{
									// Create users
									if (isset($_GET["ErrCode"]))
									{
										// read error page content from file
										// Page content was generated by Python and stored in a file
										if (isset($_GET["fd"]) && $_GET["fd"] != "")
										{
											$user_file = "/tmp/tmp" . $_GET["fd"] . ".html";
										
											$user_fh = fopen($user_file, 'r');
											$user_page = fread($user_fh, filesize($user_file));
											echo $user_page;
											
											unlink($user_file);
										}
										else
										{
											echo "Error: this username already exists";
										}
									}
									else
									{
										printUserCreationForm();
									}
								}
								else
								{
									// redirect
									// this does NOT work!!
// 									header("Location:" . $hostname . "index.php");
									?><SCRIPT LANGUAGE="javascript">window.location.href="<?php echo $_SERVER["PHP_SELF"] . "?View=6"; ?>";</script><?php
								}
							}
							
							elseif ($_GET["View"] == "2")
							{
								// delete user
								if (isset($_GET["Del"]))
								{
									echo "<span style=\"color:#0000FF; font-weight:bold;\">User deleted successfully.</span>";
								}
								else
								{		
									printSearchUserForm();

									if (isset($_POST["search_user"]))
									{
										findUser();
									}
								}
							}
							elseif ($_GET["View"] == "3")
							{
								// add lab
								if (!isset($_GET["Lab"]))
								{
									printLabCreationForm();
								}
							}
							
							elseif ($_GET["View"] == "4")
							{
								// lab detailed view
								printViewLabForm();
							}
							elseif ($_GET["View"] == "5")
							{
								// delete lab
								echo "<span style=\"color:#0000FF; font-weight:bold;\">Laboratory deleted successfully.</span><BR>";

								echo "<P><a href=\"" . $_SERVER["PHP_SELF"]. "?View=4\">Back to Lab list</a>";
							}
							elseif ($_GET["View"] == "6")
							{
								// Change password
								if (isset($_POST["change_pw"]))
								{
									$old_pw = trim($_POST["old_pw"]);
									$new_pw = trim($_POST["new_pw"]);
									$new_pw_conf = trim($_POST["new_pw_2"]);
												
									$currPW = $_SESSION["userinfo"]->getPassword();
									
									if (strcasecmp(md5($old_pw), $currPW) != 0)
									{
										printFormChangePasswd(true, false, false);
									}
									else if (strcasecmp($new_pw, $new_pw_conf) != 0)
									{
										printFormChangePasswd(false, true, false);
									}
									else if (strcasecmp($new_pw, $old_pw) == 0)
									{
										printFormChangePasswd(false, false, true);
									}
									else
									{
										mysql_query("UPDATE Users_tbl SET password=MD5('" . $new_pw . "') WHERE userID='" . $currUserID . "' AND status='ACTIVE'");
										echo "Your password has been changed successfully.  Please use the new password on your next login.";
									}
								}
								else
								{
									printFormChangePasswd();
								}
							}
							// Jan. 23/08: Order clones
							elseif ($_GET["View"] == "8")
							{
								outputOrders();
							}
							// Jan. 23/08: Remove reagents from order
							else if ($_GET["View"] == "9")
							{
// 								print_r($_POST);
								$tmpOrder = new Order_Class();
								$tmpOrder->removeFromOrder($_POST["removeFromOrder"]);
								outputOrders();
							}
							?>
						</td>
					</tr>
					<?php
				}
				else
				{
					echo "<tr><td class=\"warning\">";
					echo "Please log in to access this page.";
					echo "</td></tr>";
				}
			}
			else
			{
				// June 1, 2010: Automated password reset
				if (isset($_POST["reset_pw"]))
				{
					printFormPasswdReset();
				}
				else if (isset($_GET["Reset"]))
				{
					switch ($_GET["Reset"])
					{
						case '1':
							if (isset($_GET["uid"]))
							{
								$email = $loginBlock->getUserEmail($_GET["uid"]);
	
								echo "<span style=\"color:blue;\">A temporary password has been emailed to " . $email . ". Please change this password on your next login.</span>";
							}
							else
							{
								echo "Could not retrieve user ID.  Please contact administrator.";
							}
						break;
						
						case '0':
							echo "<span style=\"color:red\">Error setting password: Could not match the username provided to an existing OpenFreezer user account.<BR>";

							echo "<P>If you have not yet obtained an OpenFreezer user account, please <a href='mailto:" . $mail_programmer . "'>contact the administrator</a>.</span>";
						break;
						
						default:
						break;
					}
				}
				else
				{
					echo "<tr><td class=\"warning\">";
					echo "Please log in to access this page.";
					echo "</td></tr>";
				}
			}
		?>
		</table>
	</div>
	
	<?php

	outputMainFooter();
	

	/*********************************
	*	FUNCTIONS
	*********************************/

/**
 * @name Print form for addition of new users into OpenFreezer
 *
*/
function printUserCreationForm()
{
	global $cgi_path;
	global $conn;
	
	// Duplicate username error
	$showUsernameWarning = (isset($_GET["ErrCode"]) && ($_GET["ErrCode"] == 'Dup_un')) ? "inline" : "none";
	
	// get username from session
	$currUserName = $_SESSION["userinfo"]->getDescription();
	?>
		<FORM NAME="create_user_form" METHOD="POST" ACTION="<?php echo $cgi_path . "user_request_handler.py"; ?>" onSubmit="return verifyAddUser();">
			<!-- Pass user info as a hidden form value - currently the most secure way to pass session info from PHP to Python -->
			<INPUT type="hidden" ID="curr_username_hidden" NAME="curr_username" VALUE="<?php echo $currUserName; ?>">

			<TABLE width="760px" cellpadding="5" cellspacing="5">
			
				<TH colspan="4" style="color:#0000FF; border-top:1px groove black; border-bottom: 1px groove black; padding-top: 10px; padding-top:5px;">
					ADD NEW USER
					<P style="color:#FF0000; font-weight:normal; font-size:8pt; margin-top:5px;">Fields in red marked with an asterisk (<span style="font-size:9pt; color:#FF0000;">*</span>) are mandatory</P>
				</TH>
				
				<TR>
					<TD style="width:150px; vertical-align:top; padding-top:10px; color:#FF0000;">
						Laboratory:&nbsp;<sup style="font-size:10pt; color:#FF0000;">*</sup>
					</TD>
					
					<TD style="vertical-align:top; padding-top:10px">
						<?php printLabList(); ?>
						<BR/>
						<P id="lab_warning" style="color:#FF0000; display:none">Please select a laboratory name from the dropdown list above.</P>
					</TD>
				</TR>
				
				<TR>
					<TD class="createViewColName" style="color:#FF0000;">
						Username:&nbsp;<sup style="font-size:10pt; color:#FF0000;">*</sup>
					</TD>

					<TD class="createViewColValue">
						<INPUT TYPE="TEXT" SIZE="35px" id="user_name" NAME="username"/>
						<BR/>
						<!-- Warning anchor -->
						<a name="w1" style="text-decoration:none; font-weight:normal; font-size:8pt">
						<P id="dup_uname_warning" style="color:#FF0000; display:<?php echo $showUsernameWarning; ?>">This username already exists.  Please specify a different username.</P>
						</a>
					</TD>

					<TD style="font-size:8pt">
<!-- 						Alphanumeric string up to 10 characters used to log into the system. -->
					</TD>
				</TR>
				
				<TR>
					<TD class="createViewColName" style="color:#FF0000;">
						First name:&nbsp;<sup style="font-size:10pt; color:#FF0000;">*</sup>
					</TD>

					<TD class="createViewColValue">
						<INPUT TYPE="TEXT" SIZE="35px" id="first_name" NAME="firstName"/>
					</TD>
				</TR>
					
				<TR>
					<TD class="createViewColName" style="color:#FF0000;">
						Last name:&nbsp;<sup style="font-size:10pt; color:#FF0000;">*</sup>
					</TD>

					<TD class="createViewColValue">
						<INPUT TYPE="TEXT" SIZE="35px" id="last_name" NAME="lastName"/>
					</TD>
				</TR>
				
				<TR>
					<TD class="createViewColName">
						Email:
					</TD>

					<TD class="createViewColValue">
						<INPUT TYPE="TEXT" SIZE="35px" id="e_mail" NAME="email"/>
					</TD>
				</TR>
				
				<TR>
					<TD>
						Access Level:
					</TD>

					<TD colspan="3">
						<INPUT TYPE="RADIO" name="system_access_level" value="Reader" style="margin-top:8px; font-size:9pt" checked onClick="showHideWriteProjectAccess()">Reader<BR/>
						<INPUT TYPE="RADIO" name="system_access_level" value="Writer" style="margin-top:8px; font-size:9pt" onClick="showHideWriteProjectAccess()">Writer<BR/>
						<INPUT TYPE="RADIO" name="system_access_level" value="Creator" style="margin-top:8px; font-size:9pt" onClick="showHideWriteProjectAccess()">Creator<BR/>
						<INPUT TYPE="RADIO" name="system_access_level" value="Admin" style="margin-top:8px; font-size:9pt" onClick="showHideWriteProjectAccess()">Admin<BR/>
					</TD>
				</TR>
				
				<!-- Modified Sept. 9/07: Hide Write access section by default, only show if the new user is made non-reader -->
				<TR>
					<TD colspan="4">
						<TABLE id="write_project_access" style="display:none" width="100%">
							<TR>
								<TD colspan="4" style="border-top:1px groove black; border-bottom:1px groove black; padding-top:8px; font-size:8pt; font-weight:bold;">
									Grant project access permissions to this user:<BR>
									<span id="read_note" style="display:table-row; font-size:8pt; font-weight:normal; margin-top:10px;">Select one or more projects from the list above and press 
									<input style="margin-top:8px" onclick="addProjects('packetListWrite', getSelectedRole('1'))" value="Go" type="button"></INPUT></span><BR>
								</TD>
							</TR>

							<TR>
								<TD colspan="4" nowrap>
									<?php 
										printProjectList('packetListWrite');
									?>
									<BR>

									<!-- April 3/09: Changed function name from selectAll() to selectAll() (renamed function in menu.js for generalization, it can be used to select all elements in any list, not just Users) -->
									<INPUT TYPE="checkbox" style="margin-top:10px; font-size:8pt;" onClick="selectAll(this.id, 'packetListWrite')" id="add_all_chkbx"> Select All</INPUT>
								</TD>
							</TR>
	
							<TR>
								<TD style="vertical-align:top" colspan="3">
									<span style="font-size:8pt; font-weight:bold">User's access level to selected projects:<BR/></span>
									<input type="radio" id="access_level_radio_read" name="access_levels" value="read" style="margin-top:8px; font-size:9pt" checked>Read-Only &nbsp;&nbsp;&nbsp;<BR/>
									<input type="radio" id="access_level_radio_write" name="access_levels" value="write" style="margin-top:5px; font-size:9pt">Write &nbsp;&nbsp;&nbsp;<BR/>
									<input style="margin-top:8px" onclick="addProjects('packetListWrite', getSelectedRole('1'))" value="Go" type="button"></INPUT>

									<P style="font-size:8pt; border-top:1px groove black; padding-top:10px; padding-bottom:5px; margin-top:10px">
									Access levels: <BR/>
									<span style="font-size: 8pt; margin-left: 9px; font-weight:bold; ">&#45; Read-Only:</span>  May view reagents in a project but may NOT modify them or add new reagents<BR/>

									<span style="font-size: 8pt; margin-left: 9px; font-weight:bold;">&#45; Write:</span>  May create and modify reagents in a project but may NOT change project details or add/remove members to/from the project<BR/>
									</P>
								</TD>
							</TR>

							<TR>
								<TD colspan="4" style="border-top:1px groove black; border-bottom:1px groove black; font-size:8pt; font-weight:bold">
									User's current project access privileges:
								</TD>
							</TR>

							<TR>
								<TD style="border-right:1px solid black; font-size:8pt">
									<B>Read-Only</B><BR/>
									<SELECT id="user_projects_readonly" name="userProjectsReadonly" style="margin-top:5px" multiple size="12">
									<?php
										// August 10/07: Default reader access to all on public projects
										$publicProjects = getPublicProjects();

										foreach ($publicProjects as $key => $tmpProj)
										{
											$pID = $tmpProj->getPacketID();
											$pName = $tmpProj->getName();
											
											// added Oct. 5, 2010
											$pOwner = $tmpProj->getOwner();
											
											// concatenate project ID and name in the form '1:parent'
// Oct. 5, 2010										$tmpDescr = $pID . ": " . $pName;

											// replaced Oct. 5, 2010
											$tmpDescr = $pID . ": " . $pOwner->getLastName() . ": " . $pName;
											
											echo "<OPTION VALUE=\"" . $pID . "\">" . $tmpDescr . "</OPTION>";
										}
									?>
									</SELECT><BR/>

									<!-- April 3/09: Changed function name from selectAll() to selectAll() (renamed function in menu.js for generalization, it can be used to select all elements in any list, not just Users) -->
									<INPUT style="margin-top:10px;" TYPE="checkbox" onClick="selectAll(this.id, 'user_projects_readonly')" id="select_all_reader_chkbx"> Select All</INPUT>
								</TD>

								<TD style="text-align:center; width:100px; border-right: 1px solid black; padding-left:20px; padding-right:20px;">
									<input onclick="addProjects('user_projects_readonly', 'write')" value="   Make Writeable >>" type="button"></INPUT><BR/>
									<input style="margin-top:30px;" onclick="addProjects('user_projects_write', 'read')" value="<< Make Read-Only" type="button"></INPUT><BR/>
									<input style="margin-top:30px;" 	onclick="addProjects('user_projects_write', 'rmv_write'); addProjects('user_projects_readonly', 'rmv_write')" value="Remove Selected" type="button"></INPUT>
								</TD>

								<TD style="padding-left:50px; font-size:8pt">
									<B>Write</B><BR/>
									<SELECT id="user_projects_write" name="userProjectsWrite" style="margin-top:5px" multiple size="12"></SELECT><BR/>


									<!-- April 3/09: Changed function name from selectAll() to selectAll() (renamed function in menu.js for generalization, it can be used to select all elements in any list, not just Users) -->
									<INPUT style="margin-top:10px;" TYPE="checkbox" onClick="selectAll(this.id, 'user_projects_write')" id="select_all_writer_chkbx"> Select All</INPUT>
								</TD>
							</TR>

							<TR>
								<TD colspan="4" style="border-top:1px groove black; border-bottom:1px groove black">
									<INPUT TYPE="SUBMIT" id="addUser" NAME="add_user" VALUE="Add User" onClick="selectAllElements('user_projects_readonly'); selectAllElements('user_projects_write');">
								</TD>
							</TR>
						</TABLE>

						<!-- Sept. 9/07: Show Read project section by default; if user is made non-reader, replace it with Write section -->
						<TABLE id="read_project_access" width="100%">
							
							<!-- Update Oct. 4, 2010 -->
							<th colspan="100%" style="color:blue; border-top:1px ridge black; padding-top:8px; font-size:9pt; text-align:left; padding-left:5px;">Grant project access permissions to the user:<BR></th>

							<TR>
								<TD style="vertical-align:top; font-size:9pt; padding-top:5px; padding-left:5px; width:400px; font-weight:bold;">
									Select projects:<BR><P>
								
									<table border="0">
										<TR>
											<td width="75px" colspan="2" style="vertical-align:top;"><input type="radio" name="select_projects" checked onclick="document.getElementById('searchByMembers').style.display='none'; document.getElementById('searchByLab').style.display=''; hideUserProjects(); hideKeywd(); hideAllProjects();">By lab:
												<SPAN ID='searchByLab' style="vertical-align:top; margin-left:40px;"><?php printLabList("onChange=\"showLabProjects('projectLabID');\"", "", "projectLabID", ""); ?></SPAN>
											</TD>
										</TR>
									
										<TR>
											<TD colspan="2" ID="project_read_checkbox" style="white-space:nowrap; display:none;">
											<?php
												$labList = getLabList();
									
												foreach ($labList as $labID => $labName)
												{
													$labProjects = getLabProjects($labID);

													if (sizeof($labProjects) > 0)
													{
														echo "<SELECT MULTIPLE id=\"lab_projects_" . $labID . "\" style=\"margin-left:10px; display:" . $display . "\">";

														foreach ($labProjects as $packetID => $tmpProjTxt)
														{
															echo "<OPTION ID=\"lab_" . $labID . "_project_" . $packetID . "\" VALUE=\"" . $packetID . "\">" . $tmpProjTxt . "</OPTION>";
														}

														echo "</SELECT>";

														?><div style="margin-top:10px;" id="selectAllCaption_<?php echo $labID; ?>"><INPUT TYPE="checkbox" id="readonly_add_chkbx_<?php echo $labID; ?>" style="margin-left:5px; font-size:8pt;" onClick="selectAll(this.id, '<?php echo "lab_projects_" . $labID; ?>')"> Select All</INPUT></div><?php
													}
													else
														echo "<span ID=\"no_projects_" . $labID . "\" style=\"color:#EF4A11; padding-left:10px; display:" . $display . "\">No projects available</span>";

												}

												?>
											</TD>

											<TD style="vertical-align:top;">
												<DIV ID="projectCaption" style="display:none; padding-left:20px; white-space:nowrap; padding-top:10px; font-size:8pt; font-weight:bold;">
													<input ID="addReadProjects" onclick="addProjects('packetListRead', 'readonly')" value="Add >>" type="button"></INPUT><BR><P>

													<input ID="readonly_remove_btn" onclick="moveProjectToLabListSpecific('user_projects_read');" value="Remove" type="button"></INPUT>
												</DIV>
											</td>
										</TR>

										<TR>
											<td colspan="2" style="vertical-align:top; white-space:nowrap;"><input type="radio" name="select_projects" onclick="document.getElementById('searchByLab').style.display='none'; document.getElementById('searchByMembers').style.display=''; hideLabProjects(); hideKeywd(); hideAllProjects();" colspan="3">By owner:
											<?php
												echo "<SELECT id=\"searchByMembers\" style=\"margin-left:12px; display:none;\" onChange=\"showUserProjects(this[this.selectedIndex].value);\">";

												echo "<OPTION SELECTED value=\"default\">Select Owner</OPTION>";

												$users = findAllProjectOwners();

												// Need to print users in alphabetical order, but calling sort() on $users gets rid of the userIDs as array keys.  Use two dictionaries to sort by value and preserve keys.

												// userName => userID
												$uNameIDs = array_flip($users);

												$userIDs = array_keys($users);
												$userNames = array_values($users);

												sort($userNames);

												foreach ($userNames as $key => $value)
												{
													$userName = $value;
													$userID = $uNameIDs[$userName];

													echo "<OPTION value=\"" . $userID . "\">" . $userName . "</OPTION>";
												}
										
												echo "</SELECT>";
											?></TD>
										</TR><?php

												// show projects for each user, hidden initially
												foreach ($userNames as $key => $value)
												{
													$userName = $value;
													$userID = $uNameIDs[$userName];

													// find projects owned by selected user
													$uPackets = Array();

													echo "<TR style=\"display:none;\" ID=\"" . $userID . "_projects\"><TD width=\"75px\">&nbsp;</TD><TD style=\"padding-left:23px;\">";

													echo "<SELECT ID=\"userPackets_" . $userID . "\" multiple size=\"5\">";
												
													$find_name_rs = mysql_query("SELECT p.packetID as packetID, p.packetName as packetName, u.lastname as owner FROM Packets_tbl p, Users_tbl u WHERE p.ownerID='" . $userID . "' AND p.ownerID=u.userID AND p.status='ACTIVE' ORDER BY p.packetID", $conn) or die("Error fetching packet ID:" . mysql_error());

													while ($find_name_ar = mysql_fetch_array($find_name_rs, MYSQL_ASSOC))
													{
														echo "<OPTION value=\"" . $find_name_ar["packetID"] . "\" ID=\"" . $userID . "_user_projects_" . $find_name_ar["packetID"] . "\">" .  $find_name_ar["packetID"] . ": " . $find_name_ar["owner"] . ": " . $find_name_ar["packetName"] . "</OPTION>";
													}

													echo "</SELECT></TD>";

													?><TD ID="userProjectCaption_<?php echo $userID; ?>" style="display:none; padding-left:12px; white-space:nowrap; padding-top:10px; font-size:8pt; font-weight:bold;">
														<input ID="addReadProjectsUser" value="Add >>" type="button" onclick="addProjects('userPackets_<?php echo $userID; ?>', 'readonly')"></INPUT><BR><P>
	
														<input style="margin-left:12px;" ID="user_readonly_remove_btn" onclick="moveProjectToUserListSpecific('user_projects_read');" value="Remove" type="button"></INPUT>
													</TD><?php
	
													echo "</TR>";
												}

										?><TR><td colspan="3" style="white-space:nowrap;"><input type="radio" name="select_projects" onclick="document.getElementById('searchByLab').style.display='none'; document.getElementById('searchByMembers').style.display='none'; hideUserProjects(); hideLabProjects(); showProjectKeywordSearch(); hideAllProjects();">By name (type any keyword in project name or description):</TD></TR>

										<TR ID="projectKeywdSearch" style="display:none;">
											<TD style="padding-left:15px; font-size:9pt;" colspan="2">
												LIKE %<INPUT TYPE="text" size="25" ID="project_keywd" NAME="projectKeyword">%
												<INPUT TYPE="button" style="font-size:9pt;" onclick="searchProjectByKeyword();" value="Find">
											</TD>
										</TR>
										
										<TR ID="project_search_results" style="display:none;">
											<TD style="padding-left:12px;">
												<SELECT MULTIPLE SIZE="5" ID="keywdProjectMatchList"></SELECT>
											</TD>
										
											<TD ID="keywdProjectCaption" style="padding-left:12px; white-space:nowrap; padding-top:10px; font-size:8pt; font-weight:bold;">
												<input ID="addReadProjectsKeywd" value="Add >>" type="button" onclick="addProjects('keywdProjectMatchList', 'readonly')"></INPUT><BR><P>
											
												<input ID="user_readonly_remove_btn" onclick="moveListElements('user_projects_read', 'keywdProjectMatchList', false, false);" value="<< Remove" type="button"></INPUT>
											</TD>
										</TR>
									
										<TR><td colspan="3" style="white-space:nowrap;"><input type="radio" name="select_projects" onclick="document.getElementById('searchByLab').style.display='none'; document.getElementById('searchByMembers').style.display='none'; hideUserProjects(); hideLabProjects(); hideKeywd(); showAllProjects();">View all projects:</TD></TR>

										<TR ID="viewAllProjects" style="display:none;">
											<TD>
												<?php 
													printProjectList('packetListReadAll');
												?>
												<BR>
			
												<!-- April 3/09: Changed function name from selectAll() to selectAll() (renamed function in menu.js for generalization, it can be used to select all elements in any list, not just Users) -->
												<INPUT TYPE="checkbox" style="margin-top:10px; font-size:8pt;" onClick="selectAll(this.id, 'packetListReadAll')" id="add_all_chkbx"> Select All</INPUT>
											</TD>

											<TD style="vertical-align:top;">
												<DIV ID="allProjectsCaption" style="padding-left:20px; white-space:nowrap; padding-top:10px; font-size:8pt; font-weight:bold;">
													<input ID="addReadProjects" onclick="addProjects('packetListReadAll', 'readonly')" value="Add >>" type="button"></INPUT><BR><P>

													<input ID="readonly_remove_btn" onclick="moveListElements('user_projects_read', 'packetListReadAll', true, false);" value="<< Remove" type="button"></INPUT>
												</DIV>
											</td>
										</TR>
									</table>
								</TD>

								<TD colspan="4" style="vertical-align:top; font-size:9pt; padding-top:3px; padding-bottom:5px; font-weight:bold; padding-left:5px;">
									User's current project access privileges:<BR>
									<span style="color:black; font-weight:normal; font-size:8pt;">(All users have read access to public projects)</span>

									<table>
										<TR>
											<TD style="font-size:8pt; padding-left:5px;">
												<SELECT id="user_projects_read" name="userProjectsReadonlyWrite" style="margin-top:8px" multiple size="12">
												<?php
													// August 10/07: Default reader access to all on public projects
													$publicProjects = getPublicProjects();
			
													foreach ($publicProjects as $key => $tmpProj)
													{
														$pID = $tmpProj->getPacketID();
														$pName = $tmpProj->getName();
			
														// added Oct. 5, 2010
														$pOwner = $tmpProj->getOwner();

														// replaced Oct. 5, 2010 - include owner's name
														$tmpDescr = $pID . ": " . $pOwner->getLastName() . ": " . $pName;
														
														echo "<OPTION DISABLED VALUE=\"" . $pID . "\">" . $tmpDescr . "</OPTION>";
													}
												?>
												</SELECT><BR>

												<INPUT style="margin-top:10px;" TYPE="checkbox" onClick="selectAll(this.id, 'user_projects_read')" id="readonly_rmv_chkbx"> Select All</INPUT>
<!-- 												<BR> -->
<!-- 												<span style="font-size:8pt; font-weight:normal;">To revoke access, select one or more projects from the list and press</span> -->
											</TD>
										</TR>
									</table>
								</TD>
							</TR>

							<TR>
								<TD colspan="4" style="border-top:1px groove black; border-bottom:1px groove black">
									<INPUT TYPE="SUBMIT" id="addUser" NAME="add_user" VALUE="Add User" onClick="selectAllElements('user_projects_read');">
								</TD>
							</TR>
						</TABLE>
					</TD>
				</TR>
			</TABLE>
		</FORM>

<!-- 		<FORM NAME="projectSearchForm" METHOD="POST" ACTION="<?php /*echo $cgi_path . "project_request_handler.py"; */?>"></FORM> -->
	<?php
}

// New Oct. 5, 2010, modified Oct. 6, 2010
// return a list of lab projects; will print them in calling function
/**
 * Return a list of lab projects to be printed in the calling function
 *
 * @author Marina Olhovsky <olhovsky@lunenfeld.ca>
 * @version 3.1 2010-10-05, modified Oct. 6, 2010
 *
 * @param INT $labID
 *
*/
function getLabProjects($labID)
{
	global $conn;
	$projects = Array();

	// Get all projects owned by users in this lab
	$query = "SELECT p.packetID, p.packetName, u.lastname FROM Packets_tbl p, Users_tbl u WHERE u.labID='" . $labID . "' AND u.userID=p.ownerID AND p.status='ACTIVE' ORDER BY p.packetID";

	$labProjectList = mysql_query($query, $conn) or die("Error fetching lab projects: " . mysql_error());

	while ($labProjects = mysql_fetch_array($labProjectList, MYSQL_ASSOC))
	{
		$packetID = $labProjects["packetID"];
		$packetName = $labProjects["packetName"];
		$lastname = $labProjects["lastname"];
		$tmpProjTxt = $packetID . ": " . $lastname . ": " . $packetName;

		$projects[$packetID] = $tmpProjTxt;
	}

	return $projects;
}


/**
 * Print form for users to change their password
 *
 * @author Marina Olhovsky <olhovsky@lunenfeld.ca>
 * @version 3.1
 *
 * @param boolean $curr_pw_err
 * @param boolean $new_pw_err if new password values entered do not match
 * @param boolean $old_pw_err: if old password is identical to new password
 *
*/
function printFormChangePasswd($curr_pw_err = false, $new_pw_err = false, $old_pw_err = false)
{
	global $conn;
	
	$curr_err_display = $curr_pw_err ? "table-row" : "none";
	$new_err_display = $new_pw_err ? "table-row" : "none";
	$old_err_display = $old_pw_err ? "table-row" : "none";
	
	?>
	<FORM NAME="change_passwd" METHOD="POST" ACTION="<?php $_SERVER["PHP_SELF"] . "?View=7"?>">
		
		<TABLE width="700px" cellpadding="8px" style="margin-left:20px;" border="1px outset black" frame="box" rules="all">
		
			<TR>
				<TH colspan="2" style="color:#0000FF; text-align:center; font-weight:bold">CHANGE YOUR PASSWORD</TH>
			</TR>
			
			<TR>
				<TD style="width:100px">Old Password:</TD>
				<TD><INPUT TYPE="password" ID="old_passwd" NAME="old_pw"></TD>
			</TR>
					
			<TR style="display:<?php echo $curr_err_display; ?>">
				<TD colspan="2" style="color:#FF0000; font-size:8pt;">
					The old password value is incorrect.  Please verify your input.
				</TD>
			</TR>
			
			<TR>
				<TD style="width:100px">New Password:</TD>
				<TD><INPUT TYPE="password" ID="new_passwd" NAME="new_pw"></TD>
			</TR>
			
			<TR style="display:<?php echo $old_err_display; ?>">
				<TD colspan="2" style="color:#FF0000; font-size:8pt;">
					The new password must differ from your old password.  Please select a different password value.
				</TD>
			</TR>
			
			<TR>			
				<TD style="width:150px; white-space:nowrap">Confirm New Password:</TD>
				<TD><INPUT TYPE="password" ID="new_passwd_confirm" NAME="new_pw_2"></TD>
			</TR>
			
			<TR style="display:<?php echo $new_err_display; ?>">
				<TD colspan="2" style="color:#FF0000; font-size:8pt;">
					The new password values do not match.  Please retype the new password correctly.
				</TD>
			</TR>
			
			<TR>
				<TD colspan="2" style="white-space:nowrap;">
					<INPUT TYPE="SUBMIT" NAME="change_pw" VALUE="Change" onClick="return checkNonEmptyPassword();">
				</TD>
			</TR>
		</TABLE>
	</FORM>
	<?php
}


/**
 * Print form for user deletion -- NOT actively used in this version
 * 
 * @author Marina Olhovsky <olhovsky@lunenfeld.ca>
 * @version 3.1
*/
function printUserDeletionForm()
{
	global $conn;
	global $cgi_path;
	
	// Similar to Delete Project - show a list of labs, select lab, show members list, select user, and delete without asking questions (maybe just popup a JS confirm for formality)
	?>
		<FORM NAME="delete_user_form" METHOD="POST" ACTION="<?php echo $cgi_path . "user_request_handler.py"; ?>" onSubmit="return verifyDeleteUser();">
			
			
			<TABLE width="775px" cellpadding="5" cellspacing="5">
			
				<TH colspan="3" style="color:#0000FF; border-top:1px groove black; border-bottom: 1px groove black;">
					DELETE USER
				</TH>
				
				<TR>
					<TD style="width:150px; vertical-align:top; padding-top:10px;">
						Select laboratory:&nbsp;&nbsp;
						<?php 
							printLabList("onChange=\"showLabMembersList()\""); 
						?>
					</TD>
				</TR>
				
				<TR id="deleteMembersRow" style=" display:none">
					<TD style="width:150px; vertical-align:top; padding-top:10px;">
						Select member names from the list below and press 'Add selected to Delete list' to add them to the list of candidates for deletion:<BR/><BR/>
						<?php 
							printLabMembersList();
						?>
						<BR/><BR/>
						
						<INPUT TYPE="button" id="addUserDel" VALUE="Add selected to Delete list" onClick="return checkSelectUser('lab_source_list_' + getSelectedLab(), 'deletion_candidates_list', this.id);">
						<BR/><BR/><HR/>
						
						<span style="font-weight:bold; color:#FF0000;">These users are marked for deletion:</span><BR/>
						<span style="font-size:9pt; padding-top:15px; padding-bottom:15px;">To remove a user from this list, select the user's name and press 'Return selected to Users list'</span><BR/>
						
						<SELECT style="margin-top:5px;" id="deletion_candidates_list" name="deletionCandidates" multiple size="12"></SELECT><BR/><BR/>
						
						<INPUT TYPE="button" id="rmvUserDel" VALUE="Return selected to Users list" onClick="return checkSelectUser('deletion_candidates_list', 'lab_source_list_' + getSelectedLab(), this.id);"><BR/><BR/>
					</TD>
				</TR>
				
				<TR>
					<TD style="width:150px; vertical-align:middle; border-top:1px groove black; border-bottom: 1px groove black; padding-top:6px; padding-bottom:6px;">
						<INPUT TYPE="SUBMIT" id="deleteUserBtn" NAME="delete_user" VALUE="Delete Users" disabled onClick="selectAllElements('deletion_candidates_list')">
					</TD>
				</TR>
			</TABLE>
		</FORM>
	<?php	
}


/**
 * Print form for searching users; give option to select search criteria
 *
 * @author Marina Olhovsky <olhovsky@lunenfeld.ca>
 * @version 3.1
*/
function printSearchUserForm()
{
	// Determine if this is our first visit to this page or whether we've arrived here after a search, in which case checkbox values have been set
	
	// lab
	if (isset($_POST["lab_criteria"]))
	{
		$lab_display = "table-row";
		$lab_checked = "checked";
	}
	else
	{
		$lab_display = "none";
		$lab_checked = "";
	}

	
	// first name
	if (isset($_POST["first_name_criteria"]))
	{
		$fn_display = "table-row";
		$fn_checked = "checked";
		$post_fn = $_POST["firstname"];
	}
	else
	{
		$fn_display = "none";
		$fn_checked = "";
		$post_fn = "";
	}
	
	
	// last name
	if (isset($_POST["last_name_criteria"]))
	{
		$ln_display = "table-row";
		$ln_checked = "checked";
		$post_ln = $_POST["lastname"];
	}
	else
	{
		$ln_display = "none";
		$ln_checked = "";
		$post_ln = "";
	}
	?>
	<FORM METHOD="POST" NAME="findUserForm" ACTION="<?php echo $_SERVER["PHP_SELF"] . "?View=2"; ?>">
		<TABLE width="100%" cellpadding="5" cellspacing="5">
			<TH colspan="3" style="color:#0000FF; padding-left:25px">
				SEARCH USERS
			</TH>
			
			<TR>
				<TD colspan="2">
					Please select attributes to include in your search:
				</TD>
			</TR>
			
			<TR>
				<TD style="vertical-align:top">
					<INPUT TYPE="checkbox" name="lab_criteria" onClick="showLabList()" <?php echo $lab_checked; ?>>&nbsp;Lab:
				</TD>
			</TR>

			<TR id="labList" style="display:<?php echo $lab_display; ?>">
				<TD style="vertical-align:top">
					<?php 
						printLabList("", "multiple");
					?>
				</TD>
			</TR>
						
			<TR>
				<TD>
					<INPUT TYPE="checkbox" name="first_name_criteria" onClick="showFirstName()" <?php echo $fn_checked; ?>>&nbsp;First name <span style="font-size:7pt">(LIKE quantitation applies to partial entries, no wildcards required):</span>
					
					<SPAN id="firstNameField" style="display:<?php echo $fn_display; ?>">
						LIKE %&nbsp;<INPUT TYPE="TEXT" SIZE="20" ID="fName" NAME="firstname" VALUE="<?php echo $post_fn; ?>">&nbsp;%
					</SPAN>
			</TR>
			
			<TR>
				<TD>
					<INPUT TYPE="checkbox" name="last_name_criteria" onClick="showLastName()" <?php echo $ln_checked; ?>>&nbsp;Last name <span style="font-size:7pt">(LIKE quantitation applies to partial entries, no wildcards required):</span>

					<SPAN id="lastNameField" style="display:<?php echo $ln_display; ?>">
						LIKE %&nbsp;<INPUT TYPE="TEXT" SIZE="20" ID="lName" NAME="lastname" VALUE="<?php echo $post_ln; ?>">&nbsp;%
					</SPAN>
			</TR>
			
			<TR>
				<TD>
					<INPUT TYPE="SUBMIT" NAME="search_user" VALUE="Submit">
				</TD>
			</TR>
		</TABLE>
	</FORM>
	<?php
}

/**
 * Search the database for a user matching the search parameters (from $_POST variables)
 *
 * @author Marina Olhovsky <olhovsky@lunenfeld.ca>
 * @version 3.1
 *
 * @see printUserSearchResults()
*/
function findUser()
{
	global $conn;
	
	$results = array();
	
	// Determine if any search attributes have been set
	//print_r($_POST);
	
	$query = "SELECT DISTINCT userID, firstName, lastName FROM Users_tbl u, LabInfo_tbl l WHERE ";
	
	if (isset($_POST["lab_criteria"]))
	{
		if (isset($_POST["labs"]))
		{
			$labs = $_POST["labs"];			// array
			$count = sizeof($labs);

			$query .= "(";

			foreach ($labs as $key => $labID)	// $labID is the numeric database ID of the lab
			{
				if ($count > 1)
				{
					$query .= "l.labID = '" . $labID . "' OR ";
					$count--;
				}
				else
				{
					// last lab in list - no OR in query
					$query .= "l.labID = '" . $labID . "' ";				
				}
			}

			$query .= ") AND u.labID=l.labID ";

			// Check if additional attributes are set; if yes, append 'AND' operand to query
			if (isset($_POST["firstname"]) || isset($_POST["lastname"]))
				$query .= "AND ";
		}
	}
	

	if (isset($_POST["first_name_criteria"]))
	{
		if (isset($_POST["firstname"]) && $_POST["firstname"] != "")
		{
			$firstName = $_POST["firstname"];

			$query .= "firstname LIKE '%" . $firstName . "%' ";

			if (isset($_POST["last_name_criteria"]))
				$query .= "OR ";
			else
				$query .= "AND ";
		}
	}

	if (isset($_POST["last_name_criteria"]))
	{
		if (isset($_POST["lastname"]) && $_POST["lastname"] != "")
		{
			$lastName = $_POST["lastname"];

			// need 'AND' in any case, to link to the final portion of the query
			$query .= "lastname LIKE '%" . $lastName . "%' AND ";
		}
	}

	$query .= "u.status='ACTIVE' AND l.status='ACTIVE' ORDER BY firstname";
	//print $query;
	
	$user_rs = mysql_query($query, $conn) or die("Cannot select user info: " . mysql_error());
	
	while ($users = mysql_fetch_array($user_rs, MYSQL_ASSOC))
	{
		$userID = $users["userID"];
		$fName = $users["firstName"];
		$lName = $users["lastName"];
		$description = $users["description"]; 
		
		$tmpUser = new Member_Class($userID, "", $description, "", "", "", "", "", "", "");
		$tmpUser->setFirstName($fName);
		$tmpUser->setLastName($lName);
		
		$results[] = $tmpUser;
	}
	
	printUserSearchResults($results);
}


/**
 * Print user search results (output a list of users matching the search criteria)
 *
 * @author Marina Olhovsky <olhovsky@lunenfeld.ca>
 * @version 3.1
 *
 * @param resource MySQL result set
 *
*/
function printUserSearchResults($results)
{
	global $cgi_path;

	$currUserName = $_SESSION["userinfo"]->getDescription();
	$currUserID = $_SESSION["userinfo"]->getUserID();

	?>
	<form name="lab_form" method="post" action="<?php echo $cgi_path . "user_request_handler.py"; ?>">
		<INPUT type="hidden" ID="curr_username_hidden" NAME="curr_username" VALUE="<?php echo $currUserName; ?>">
		<INPUT type="hidden" id="view_user_hidden" name="view_user">

		<TABLE>
		<?php
			echo "Found " . sizeof($results) . " users matching your search query:";

			foreach ($results as $key => $tmpUser)
			{
				?>
				<TR>
					<TD>
					<?php
						$tmpUserID = $tmpUser->getUserID();
						$tmpFirstName = $tmpUser->getFirstName();
						$tmpLastName = $tmpUser->getLastName();
						
						// the following are equivalent, but putting them both here in case later changes are anticipated
						$tmpDescr = $tmpUser->getDescription();
						$tmpFullName = $tmpFirstName . " " . $tmpLastName;
					?>
					<span class="linkShow" onClick="redirectToUserDetailedView('<?php echo $tmpUserID; ?>')"><?php echo $tmpFullName; ?></span>
					</TD>
				</TR>
				<?php
			}
		?>
		</TABLE>
	</form>		
	<?php
}

/**
 * Retrieves all the laboratories from the database
 *
 * @author Marina Olhovsky <olhovsky@lunenfeld.ca>
 * @version 3.1
 *
 * @return Array Dictionary of (labID => labName) tuples
*/
function getLabList()
{
	global $conn;

	$lab_rs = mysql_query("SELECT labID, lab_name FROM LabInfo_tbl WHERE status='ACTIVE' ORDER BY lab_name", $conn) or die("Cannot select labs: " . mysql_error());

	$labs = array();

	while ($lab_ar = mysql_fetch_array($lab_rs, MYSQL_ASSOC))
	{
		$labID = $lab_ar["labID"];
		$labName = $lab_ar["lab_name"];

		$labs[$labID] = $labName;
	}

	return $labs;
}


/**
 * Select all users from the given lab
 *
 * @author Marina Olhovsky <olhovsky@lunenfeld.ca>
 * @version 3.1
 *
 * @param INT $labID
 * @return Array Dictionary of (userID => userName) tuples
*/
function getAllUsers($labID)
{
	global $conn;

	$users = array();
	
	// June 29/07, Marina: ALL users - NOT just in or above category 'writers'
	$users_rs = mysql_query("SELECT userID, username, CONCAT(firstname, \" \", lastname) AS uname FROM Users_tbl WHERE labID='" . $labID . "' AND status='ACTIVE' ORDER BY uname", $conn) or die("Cannot fetch users: " . mysql_error());
	
	while ($users_ar = mysql_fetch_array($users_rs, MYSQL_ASSOC))
	{
		$uid = $users_ar["userID"];
		$username = $users_ar["username"];
		$uname = $users_ar["uname"];
		
		if ( strlen(trim($uname)) > 0 && $username != 'guest' )
		{
			$users[$uid] = $uname;
		}
	}
	
	return $users;
}


/**
 * Print a list of lab members
 *
 * @author Marina Olhovsky <olhovsky@lunenfeld.ca>
 * @version 3.1
 *
 * @param STRING $actn onChange action for the SELECT list
*/
function printLabMembersList($actn = "")
{
	global $conn;
	
	$labList = getLabList();
	$currLabID = $_SESSION["userinfo"]->getLabID();

	foreach ($labList as $labID => $labName)
	{
		//$display = ($labID == $currLabID) ? "inline" : "none";
		$display = "none";

		echo "<SELECT id=\"lab_source_list_" . $labID . "\" name=\"labSourceMembers_" . $labID . "\" multiple=\"multiple\" size=\"10\"  style=\"display: " . $display . "\"" . $actn . ">";
		
		$users = getAllUsers($labID);

		foreach ($users as $key => $value)
		{
			echo "<OPTION id=\"user_" . $key . "_lab_" . $labID . "\" value=\"" . $key . "\">" . $value . "</OPTION>";
		}

		echo "</SELECT>";
	}
}

/**
 * Auxiliary function to list all the laboratories in OpenFreezer in a dropdown list - single or multiple, depending on the parameters.
 *
 * Outputs a SELECT box inside a form that requires a lab list to be shown.
 *
 * Oct. 5, 2010: Added $listID parameter, in case this function is reused in one view (e.g. adding users) - assign different IDs to form elements to avoid confusion
 *
 * @author Marina Olhovsky <olhovsky@lunenfeld.ca>
 * @version 3.1
 *
 * @param STRING $actn onChange action for the SELECT list
 * @param STRING $multiple Should the lab list be multiple or single-option SELECT
 *
*/
function printLabList($actn = "", $multiple = "", $listID="labList", $listName="labs")
{
	global $conn;
	
	$labList = array();
	
	// Select list of labs from the database
	$labList_rs = mysql_query("SELECT labID, lab_name FROM LabInfo_tbl WHERE status='ACTIVE' ORDER BY lab_name", $conn) or die("Error selecting labs: " . mysql_error());
	
	while ($labList_ar = mysql_fetch_array($labList_rs, MYSQL_ASSOC))
	{
		$labID = $labList_ar["labID"];
		$labName = $labList_ar["lab_name"];
		
		$labList[$labID] = $labName;
	}
	
	$currLabID = $_SESSION["userinfo"]->getLabID();
	
	if (strcasecmp($multiple, 'multiple') == 0)
	{
		echo "<SELECT MULTIPLE id=\"" . $listID . "\" name=\"" . $listName . "[]\" " . $actn . ">";
	}
	else
	{
		echo "<SELECT id=\"" . $listID . "\" name=\"" . $listName . "\" " . $actn . ">";
		echo "<OPTION>Select Laboratory</OPTION>";
	}
	
	// If post search, show selections	
	if (isset($_POST["lab_criteria"]) && isset($_POST["labs"]))
	{
		$postLabs = $_POST["labs"];
	}

	foreach ($labList as $key => $value)
	{
		if (in_array($key, $postLabs))
			$selected = "SELECTED";
		else
			$selected = "";
		
		?><OPTION ID="<?php echo $key; ?>" NAME="lab_optn" VALUE="<?php echo $key; ?>" <?php echo $selected; ?>><?php 

		echo $value; 

		?></OPTION><?php
	}

	echo "</SELECT>";
}

/**
 * Output a list of all projects in OpenFreezer as a SELECT list
 *
 * @author Marina Olhovsky <olhovsky@lunenfeld.ca>
 * @version 3.1
 *
 * @param STRING $listID Form element ID of the SELECT list
*/

function printProjectList($listID = "packetList")
{
	global $conn;
	?>
	<SELECT id="<?php echo $listID; ?>" name="packets" multiple size="15">";
	<?php
		// Modified Oct. 4, 2010 - code taken from ColFunctOutputer_Class->output_packet()
		$userProjects = findAllProjects();
		$userProjectList = '';

		if (sizeof($userProjects) > 0)
		{
			$userProjectList = "(" . implode(",", $userProjects) . ")";
		}

		$query = "SELECT p.packetID as packetID, p.packetName as packetName, u.lastname as owner FROM Packets_tbl p, Users_tbl u WHERE p.ownerID=u.userID AND p.packetID IN " . $userProjectList . " AND p.status='ACTIVE'";

		$find_name_rs = mysql_query($query, $conn) or die("Error fetching packet ID:" . mysql_error());
	
// oct 4/10	$query = "SELECT p.packetID as packetID, p.packetName as packetName FROM Packets_tbl p WHERE p.status='ACTIVE'";

		$find_name_rs = mysql_query($query, $conn) or die("Error fetching packet ID:" . mysql_error());

		while ($find_name_ar = mysql_fetch_array($find_name_rs, MYSQL_ASSOC))
		{
			// update Oct. 4, 2010
// Oct. 4, 2010		$temp_packet = $find_name_ar["packetID"] . ": " . $find_name_ar["packetName"];
 			$temp_packet = $find_name_ar["packetID"] . ": " . $find_name_ar["owner"] . ": " . $find_name_ar["packetName"];

			echo "<OPTION value=\"" . $find_name_ar["packetID"] . "\">" . $temp_packet . "</option>";
		}
	?>
	</SELECT>
	<?php
}


/**
 * Print a form for adding a new laboratory to OpenFreezer
 *
 * @author Marina Olhovsky <olhovsky@lunenfeld.ca>
 * @version 3.1
*/
function printLabCreationForm()
{
	global $cgi_path;
	
 	$showLabCodeWarning = (isset($_GET["ErrCode"]) && ($_GET["ErrCode"] == '14')) ? "inline" : "none";

	// get username from session
	$currUserName = $_SESSION["userinfo"]->getDescription();
	?>
	<FORM NAME="create_lab_form" METHOD="POST" ACTION="<?php echo $cgi_path . "user_request_handler.py"; ?>">
		
		<!-- Pass user info as a hidden form value - currently the most secure way to pass session info from PHP to Python -->
		<INPUT type="hidden" ID="curr_username_hidden" NAME="curr_username" VALUE="<?php echo $currUserName; ?>">

		<TABLE width="770px" cellpadding="5" cellspacing="5" boirder="1" frame="box" rules="all">

			<TH colspan="3" style="color:#0000FF; border-top:1px groove black; border-bottom: 1px groove black; padding-top: 10px; padding-top:5px;">
				ADD NEW LABORATORY
				<P style="color:#FF0000; font-weight:normal; font-size:8pt; margin-top:5px;">Fields in red marked with an asterisk (<span style="font-size:9pt; color:#FF0000;">*</span>) are mandatory</P>
			</TH>

			<TR>
				<TD style="width:50px; vertical-align:middle; padding-top:10px; color:#FF0000; white-space:nowrap; font-size:8pt">
					Laboratory name:&nbsp;<sup style="font-size:10pt; color:#FF0000;">*</sup>
				</TD>

				<TD style="width:50px;">
					<INPUT TYPE="text" id="lab_name" name="labName" size="35px" value="<?php echo isset($_GET["labName"]) ? $_GET["labName"] : ""; ?>">
				</TD>
				
				<TD style="font-size:8pt; vertical-align:middle; ">
					Usually the name of the lab owner or PI followed by 'Lab' (e.g. 'Pawson Lab', 'Wrana Lab', etc.)
				</TD>
			</TR>
			
			<TR>
				<TD style="width:50px; vertical-align:middle; padding-top:15px; color:#FF0000; white-space:nowrap; font-size:8pt">
					Laboratory head:&nbsp;<sup style="font-size:10pt; color:#FF0000;">*</sup>
				</TD>

				<TD style="width:50px; vertical-align:middle; padding-top:15px;">
				<?php 
					if (isset($_GET["title"]))
						$title = $_GET["title"];
					else
						$title = "Dr.";		// default
				?>
					<SELECT ID="titlesList" NAME="titles">
						<OPTION <?php echo (strcasecmp($title, "Dr.") == 0) ? "SELECTED" : ""; ?> value="Dr.">Dr</OPTION>
						<OPTION  <?php echo (strcasecmp($title, "Mr.") == 0) ? "SELECTED" : ""; ?> value="Mr.">Mr</OPTION>
						<OPTION  <?php echo (strcasecmp($title, "Mrs.") == 0) ? "SELECTED" : ""; ?> value="Mrs.">Mrs</OPTION>
						<OPTION  <?php echo (strcasecmp($title, "Ms.") == 0) ? "SELECTED" : ""; ?> value="Ms.">Ms</OPTION>
					</SELECT>
					<INPUT TYPE="text" id="lab_head" name="labHead" size="25px" value="<?php echo isset($_GET["labHead"]) ? $_GET["labHead"] : ""; ?>">
				</TD>
				
				<TD style="font-size:8pt">
					Complete name of the lab owner or PI (e.g. 'Tony Pawson')
				</TD>
			</TR>

			<TR>
				<TD style="width:50px; vertical-align:middle; color:#FF0000; white-space:nowrap; font-size:8pt">
					Laboratory ID:&nbsp;<sup style="font-size:10pt; color:#FF0000;">*</sup>
				</TD>

				<TD style="width:50px; vertical-align:bottom;">
					<INPUT TYPE="text" id="lab_id" name="labCode" size="5px" value="<?php echo isset($_GET["labCode"]) ? $_GET["labCode"] : ""; ?>"><BR><BR>

					<SPAN id="dup_labcode_warning" style="vertical-align:bottom; color:#FF0000; display:<?php echo $showLabCodeWarning; ?>">This identifier already exists.  Please specify a different lab ID.</SPAN>
				</TD>
				
				<TD style="font-size:8pt; vertical-align:bottom;">
					A unique two-character identifier that will be used in container barcodes and other features.<BR>
					E.g. 'PW' => 'Pawson', 'GN' => 'Gingras', 'WG' => 'Woodgett', 'DN' => 'Dennis', etc.
				</TD>
			</TR>

			<TR>
				<TD style="width:50px; vertical-align:middle; white-space:nowrap; font-size:8pt;">
					Laboratory description:
				</TD>

				<TD style="width:50px; vertical-align:middle;">
					<INPUT TYPE="text" id="lab_descr" name="labDescription" size="35px" value="<?php echo isset($_GET["labDescr"]) ? $_GET["labDescr"] : ""; ?>">
				</TD>
				
				<TD style="font-size:8pt; vertical-align:bottom;">
					Optional; a detailed description of the laboratory's activity (e.g. 'Proteomics Research Laboratory')
				</TD>
			</TR>
			
			<TR>
				<TD style="width:50px; vertical-align:middle; white-space:nowrap; font-size:8pt">
					Location
				</TD>

				<TD style="width:50px; vertical-align:middle;">
					<INPUT TYPE="text" id="lab_location" name="labAddress" size="35px" value="<?php echo isset($_GET["locn"]) ? $_GET["locn"] : ""; ?>">
				</TD>
				
				<TD style="font-size:8pt; vertical-align:middle;">
					Optional; either the exact mailing address of the laboratory, the name of the city/country where the laboratory is located, or other location indicator (e.g. "MIT", "Boston, Massachusetts", or "Mount Sinai Hospital, Toronto, Ontario")
				</TD>
			</TR>

			<TR>
				<TD style="width:50px; vertical-align:middle; white-space:nowrap; font-size:8pt">
					Default access level:
				</TD>

				<TD style="font-size:8pt; vertical-align:middle; width:50px;">
					<?php
						if (isset($_GET["access"]))
							$accLev = $_GET["access"];
						else
							$accLev = "Reader";
					?>
					<INPUT TYPE="RADIO" name="system_access_level" value="Reader" style="margin-top:8px; font-size:8pt" <?php echo (strcasecmp($accLev, 'Reader') == 0) ? "checked" : ""; ?>>Reader<BR/>
					<INPUT TYPE="RADIO" name="system_access_level" value="Writer" style="margin-top:5px; font-size:8pt" <?php echo (strcasecmp($accLev, 'Writer') == 0) ? "checked" : ""; ?>>Writer<BR/>
					<INPUT TYPE="RADIO" name="system_access_level" value="Creator" style="margin-top:5px; font-size:8pt" <?php echo (strcasecmp($accLev, 'Creator') == 0) ? "checked" : ""; ?>>Creator<BR/>
					<INPUT TYPE="RADIO" name="system_access_level" value="Admin" style="margin-top:5px; font-size:8pt" <?php echo (strcasecmp($accLev, 'Admin') == 0) ? "checked" : ""; ?>>Admin<BR/>
				</TD>
				
				<TD style="font-size:8pt; vertical-align:bottom;  padding-top:7px">
					The default OpenFreezer<sup style="font-size:5pt">TM</sup> access level automatically granted to members of this lab.  This level may be overridden for individual lab members.<BR/>
					<b><u>Reader</u></b>: May browse selected reagents.  May not create or modify any reagents.<BR/>
					<b><u>Writer</u></b>: May create and modify reagents.  Cannot create new projects.<BR/>
					<b><u>Creator</u></b>: May create new projects in OpenFreezer<sup style="font-size:5pt">TM</sup>.  May not add members to the system.<BR/>
					<b><u>Admin</u></b>: May add new users and laboratories to OpenFreezer<sup style="font-size:5pt">TM</sup>.
				</TD>
			</TR>
		</TABLE>
		<INPUT TYPE="SUBMIT" NAME="add_lab" VALUE="Add Laboratory" onClick="return checkLab();">
	</FORM>
	<?php
}


/**
 * @name Find a list of users who are currently listed as project owners
 * @return Array list of user IDs
 *
 * @author Marina Olhovsky
 * @version 2010-10-08
*/
function findAllProjectOwners()
{
	global $conn;

	$users = Array();

	$query = "SELECT userID, description FROM Users_tbl u, Packets_tbl p WHERE u.userID=p.ownerID AND p.status='ACTIVE'";

	$owners_rs = mysql_query($query, $conn);

	while ($owners_ar = mysql_fetch_array($owners_rs, MYSQL_ASSOC))
	{
		$userID = $owners_ar["userID"];
		$userName = $owners_ar["description"];
		$users[$userID] = $userName;
	}

	return $users;
}

/**
 * Print a list of laboratories inside a form (in response to 'Search labs' menu selection)
 *
 * @author Marina Olhovsky <olhovsky@lunenfeld.ca>
 * @version 3.1
 *
 * @uses printLabList()
*/
function printViewLabForm()
{
	global $cgi_path;
	
	// get username from session
	$currUserName = $_SESSION["userinfo"]->getDescription();
	$currUserID = $_SESSION["userinfo"]->getUserID();
	?>
	<FORM NAME="view_lab_form" METHOD="POST" ACTION="<?php echo $cgi_path . "user_request_handler.py"; ?>">
		<FIELDSET>
		<LEGEND>&nbsp;Please select a laboratory from the dropdown list below for viewing and/or editing:&nbsp;</LEGEND>
		<!-- Pass user info as a hidden form value - currently the most secure way to pass session info from PHP to Python -->
		<INPUT type="hidden" ID="curr_username_hidden" NAME="curr_username" VALUE="<?php echo $currUserName; ?>">
		<INPUT type="hidden" ID="curr_userid_hidden" NAME="curr_user_id" VALUE="<?php echo $currUserID; ?>">
			<?php
				printLabList();
			?>
			&nbsp;&nbsp;&nbsp;<INPUT TYPE="SUBMIT" id="viewLab" NAME="view_lab" VALUE="Go">
		</FIELDSET>
	</FORM>
	<?php
}


/**
 * Print a form for users to ask to reset their password (fill in username/full name and a temporary password will be emailed if a matching email address is found)
 *
 * @author Marina Olhovsky <olhovsky@lunenfeld.ca>
 * @version 3.1 2010-06-01
 *
*/
function printFormPasswdReset()
{
	global $cgi_path;

	?><FORM METHOD="POST" ACTION="<?php echo $cgi_path . "user_request_handler.py"; ?>">
		<TABLE width="960px" cellpadding="8px" style="margin-left:20px;">
			<TR>
				<TD style="padding-left:10px;">
					Please enter your OpenFreezer username:<BR><P>
					<INPUT TYPE="TEXT" SIZE="25px" NAME="uName" ID="uname_remind">
					<BR><BR>
					<span class="linkShow" onClick="document.getElementById('showUserDescrRow').style.display='table-row';">I forgot my username</span>
				</td>
			</tr>

			<TR ID="showUserDescrRow" style="display:none;">
				<TD style="padding-left:10px;">
					If you do not remember your username, please enter your full name (first and last):
					<P><INPUT TYPE="TEXT" SIZE="45px" NAME="uDesc" ID="udesc_remind">
				</td>
			</TR>

			<TR>
				<TD style="padding-left:10px; padding-top:10px;">
					<INPUT TYPE="SUBMIT" NAME="reset_pw" VALUE="Submit" onClick="return checkPasswordReminder();">
					<BR><?php 
						echo "<P>If you have not yet obtained an OpenFreezer user account, please <a href='mailto:" . $mail_programmer . "'>contact the administrator</a>.</span>";
					?>
				</TD>
			</TR>
		</TABLE>
	</form><?php
}

/**
 * Print a list of user's clone orders, which can be emailed to clone_request
 *
 * @author Marina Olhovsky <olhovsky@lunenfeld.ca>
 * @version 3.1
 *
 * @uses Member_Class::getOrders()
*/
function outputOrders()
{
	global $cgi_path;
	global $hostname;
	
	$gfunc_obj = new generalFunc_Class();
	$lfunc_obj = new Location_Funct_Class();

	// get username from session
	$currUserName = $_SESSION["userinfo"]->getDescription();
	$currUserID = $_SESSION["userinfo"]->getUserID();

	// June 30, 2010
	$currUserLabID = $_SESSION["userinfo"]->getLabID();
	$currUserLabName = $_SESSION["Lab_ID_Name"][$currUserLabID];

	if (!isset($_GET["Sent"]))
	{
		?>
		<FORM NAME="view_lab_form" METHOD="POST" ACTION="<?php echo $cgi_path . "user_request_handler.py"; ?>">

		<!-- Pass user info as a hidden form value - currently the most secure way to pass session info from PHP to Python -->
		<INPUT type="hidden" ID="curr_username_hidden" NAME="curr_username" VALUE="<?php echo $currUserName; ?>">
		<INPUT type="hidden" ID="curr_userid_hidden" NAME="curr_user_id" VALUE="<?php echo $currUserID; ?>">

		<?php
			$userOrders = $_SESSION["userinfo"]->getOrders();

			if (sizeof($userOrders) == 0)
			{
				?><SPAN style="color:#0000FF;">You have no pending orders.</SPAN><BR><?php
			}
			else
			{
				?><SPAN style="color:#000000;">Reagents in your pending order:</SPAN><BR><?php
				
				$orderDate = date('Y-m-d');

				// June 2, 2011: Dorothy's suggestion: include sequence
				$outputContent = "Request Date,Requested By,Laboratory,LIMS ID,Gene Name,Accession Number,Plate,Well,Resistance,Verification,Project #,Restrictions on Use,Handout Date,Picked By,Sequence\r";

				foreach ($userOrders as $key => $order)
				{
					$reagentID = $order->getReagentID();
					$isoNum = $order->getIsolateNumber();
					$contID = $order->getContainerID();
					$row = $order->getRow();
					$col = $order->getColumn();
					$orderKey = $order->getOrderKey();
					
					// June 2, 2011: sequence
					$seq = $order->getSequence();

					// These properties may have multiple values - BUT: Dec. 16/08 - Check first if multiple; if the value is not an array, implode() won't work and will end up with a blank value!!!
// 					$name = implode("; ", $order->getName());

					// Dec. 16/08: Need to explicitly check whether the value is an array - won't output single values otherwise
					if (is_array($order->getName()))
						$name = implode("; ", $order->getName());
					else
						$name = $order->getName();

// 					$resistance = implode("; ", $order->getResistance());

					// Dec. 16/08: Need to explicitly check whether the value is an array - won't output single values otherwise
					if (is_array($order->getResistance()))
						$resistance = implode("; ", $order->getResistance());
					else
						$resistance = $order->getResistance();

					// Feb, 16, 2011: Ditto for accessions from Insert
					if (is_array($order->getAccession()))
						$accession = implode("; ", $order->getAccession());
					else
						$accession = $order->getAccession();

// 					$verification = implode("; ", $order->getVerification());

					// Dec. 16/08: Need to explicitly check whether the value is an array - won't output single values otherwise
					if (is_array($order->getVerification()))
						$verification = implode("; ", $order->getVerification());
					else
						$verification = $order->getVerification();

					$project = $order->getProject();	// Dec. 16/08

					// Dec. 16/08: Need to explicitly check whether the value is an array - won't output single values otherwise
					if (is_array($order->getRestrictions()))
						$restrictions = implode("; ", $order->getRestrictions());
					else
						$restrictions = $order->getRestrictions();

					echo "<P><INPUT TYPE=\"checkbox\" NAME=\"removeFromOrder[]\" VALUE=\"" . $orderKey . "\">";
	
					echo "&nbsp;&nbsp;<a href=\"" . $hostname . "Location.php?View=2&Mod=" . $contID . "&Row=" . $row . "&Col=" . $col . "#focus_" . $row . "_" . $col . "\">" . $gfunc_obj->getConvertedID_rid($reagentID) . "-" . $isoNum . "</a>&nbsp;&nbsp;" . $lfunc_obj->getContainerName($contID) . "&nbsp;" . $lfunc_obj->getLetterRow($row) . ":" . $col . "<BR>";

					$outputContent .= $orderDate . "," . $currUserName . "," . $currUserLabName . "," . $gfunc_obj->getConvertedID_rid($reagentID) . "-" . $isoNum . "," . $name . "," . $accession . "," . $lfunc_obj->getContainerName($contID) . "," . $lfunc_obj->getLetterRow($row) . ":" . $col . "," . $resistance . "," . $verification . "," . $project . "," . $restrictions . ",,," . $seq . "\r";
				}

				// Dump content into a file (March 27/08 - Don't use temp, use the user's name as his/her unique order identifier)
// 				$orderFileName = tempnam("/tmp", "tmp") . ".csv";
				$tmp_name_ar = explode(" ", $currUserName);
				$tmp_uname = implode("_", $tmp_name_ar);

				$orderFileName = "/tmp/" . $tmp_uname . "_Clone_Request.csv";		// caution, check it's unique
				$orderFile = fopen($orderFileName, 'w+');
				fwrite($orderFile, $outputContent);
				rewind($orderFile);

				?>
				<INPUT TYPE="hidden" NAME="outputContent" VALUE="<?php echo $orderFileName /*$outputContent*/; ?>">

				<P>&nbsp;&nbsp;&nbsp;&nbsp;<INPUT TYPE="BUTTON" id="removeFromOrder" value="Remove Selected" onClick="changeFormAction('view_lab_form', '<?php echo $_SERVER["PHP_SELF"] . "?View=9"?>')">

				<!--PERMANENT -->
				&nbsp;&nbsp;&nbsp;&nbsp;<INPUT TYPE="SUBMIT" id="sendOrder" NAME="send_order" VALUE="Send Order">

				<!-- TEMPORARY!!!!!!!!! -->
<!-- 				&nbsp;&nbsp;&nbsp;&nbsp;<INPUT TYPE="SUBMIT" id="sendOrder" NAME="send_order" VALUE="Export to Excel" onClick="toExcel('<?php /*echo $outputContent;*/ ?>');"> -->

				<P><SPAN style="font-weight:bold"><u>Please note</u>: The order list is cleared when you exit the system.  Please make sure you export your order before logging out.</SPAN>
				<?php
			}
		?>
		</FORM>
		<?php
	}
	else
	{
		if ($_GET["Sent"] == 1)
		{
			// Clear user's order list
			$_SESSION["userinfo"]->setOrders(null);

			?><SPAN style="color:#0000FF;">Your request has been submitted successfully.  A copy has been sent to your email address.  Please retain this copy for your records.</SPAN><BR><?php
		}
	}
}

mysql_close($conn);
?>
